### ISSUE TITLE
Suggestion: Yes for All prompt for replacing files in the Archive Explorer

### ISSUE THREAD

**Issue by costantino2000** [RayCarrot/RayCarrot.RCP.Metro#10]
When I had to replace some textures from the textures.cnt file of Rayman 2 I had click Ok for every texture I had to replace. Since those textures were more than one hundred it required some time.
Now, I just discovered that this is not an issue if you open the folder from the context menu action "import and convert", but a prompt for replacing all textures with the same name for those like me who selected the files with the + button and ctrl a would be nice to have.
Alternatively, a hint in the replace dialog that says something like "if you selected a lot of textures and you need to replace them it's suggested to stop and use the import and convert function instead".

**Comment by RayCarrot** [comment]
When replacing existing files I would normally recommend importing from the directory as the plus button is more meant for adding new files. But that might not be very clear initially, and having to confirm replacing the file hundreds of times is obviously not ideal! So thanks for bringing this to my attention! I think I might change the prompt to say something along the lines of "Some files have the same name as existing files. Do you want to replace them?" and have that confirm replacing all file conflicts.

**Comment by costantino2000** [comment]
What about also showing a dropdown list with all the duplicate file names? For the sake of knowing what is going to be replaced

**Comment by RayCarrot** [comment]
The current message dialog control I made doesn't support drop-down lists like that and I'd rather not add a special case just for this. What I could do though is to list say the first 10 file conflicts as text in the dialog. This would then give you an idea of which files are the issue. I don't think there's be much of a difference to the user if they only see the first 10 vs. all of them (and if the user only selects a single file it will always show that name if it has a conflict).
