### ISSUE TITLE
pls provide linux binarys

### ISSUE THREAD

**Issue by LethalManBoob** [RayCarrot/RayCarrot.RCP.Metro#11]
us rayman fans on linux do not have such luck :(

**Comment by RayCarrot** [comment]
Sorry but that's sadly not possible. It's made in WPF which is Windows-only. The only solution would be to run it in something like Wine, although I've heard it's hard setting it up there.

**Comment by LethalManBoob** [comment]
yeah its busted in wine. ill submit a wine bug report

**Comment by Cwpute** [comment]
I'd jsut like to add my request here for Linux support. This would be much more helpful for the less tech-savvy people who use linux (eg. kids) so they can safely install mods and updates and all.
Here is hope a rewrite can be considered :)
