### ISSUE TITLE
Add support for UPlay Rayman Raving Rabbids EXE Patching

### ISSUE THREAD

**Issue by Fancy2209** [RayCarrot/RayCarrot.RCP.Metro#16]
As said above, the Ubisoft Connect version of the game does not support exe patching.
![image](https://user-images.githubusercontent.com/64917206/213759190-4e0a5e4b-a847-4f91-90b9-0943b4805b3f.png)
Memory Mods work just fine tough.

**Comment by RayCarrot** [comment]
As it turns out the Ubisoft Connect exe is near identical to the one used in the GOG version, so I've updated the code to detect this exe as the GOG one and allow that to be used for the mod. I'll release a new update with this tomorrow!

**Comment by Fancy2209** [comment]
Thank you!
