### ISSUE TITLE
Add silent install flags for installing RCP

### ISSUE THREAD

**Issue by superusercode** [RayCarrot/RayCarrot.RCP.Metro#18]
Would make it easier to add to the package managers like chocolatey and winget.  The current chocolatey package operates by taking apart the installer exe (https://github.com/manuth/RaymanControlPanel-Choco/blob/main/rayman-controlpanel/tools/chocolateyInstall.ps1) where it would be easier to just have a silent flag that hides the prompts.

**Comment by RayCarrot** [comment]
Rayman Control Panel doesn't have an installer, so I'm not really sure what you mean. It's a single exe file you download and run. The only prompt you get when starting the first time is the license agreement and welcome window, but that's a part of the app itself.
