### ISSUE TITLE
Windows 11 compatibility (Rayman 2 from disc)

### ISSUE THREAD

**Issue by Erikk26** [RayCarrot/RayCarrot.RCP.Metro#19]
Hey!

Sorry for bothering but is this mod compatible with Windows 11?
Just because i have no clue why couldn't i manage to start Rayman 2 after installing it with this program...

**Comment by RayCarrot** [comment]
Hi! The disc version of Rayman 2 sadly doesn't work very well on modern systems. The installer in RCP simply installs the game, but doesn't set up any compatibility fixes for it. You might be able to get it work using things like DgVoodoo, but in general I'd recommend the digital [GOG version](https://www.gog.com/en/game/rayman_2_the_great_escape) instead. It goes on sale quite often and is very cheap.
