### ISSUE TITLE
10.3.1 Fails to install - exceptions on Win10 latest

### ISSUE THREAD

**Issue by mintyc** [RayCarrot/RayCarrot.RCP.Metro#2]
Using latest Win10 pro
Attempting to run Rayman Control Panel.exe either as administrator or regular (with no compatibility settings)

Splash screen says Rayman Origins not found,
(it is one of many rayman legacy and modern games that is actually installed)
followed by windows exception dialog boxes and the crashlog.

[crashlog.txt](https://github.com/RayCarrot/RayCarrot.RCP.Metro/files/5826430/crashlog.txt)

**Comment by RayCarrot** [comment]
Most likely there's an issue with the RCP app data not being upgraded correctly from an app update. I'll add a check for any invalid app data fields in the next update to avoid any similar issues from happening again. In the meantime you can delete your current app data for the program by deleting the files at `%localappdata%\Rayman Control Panel\RCP_Metro`
Please let me know if you have not previously updated RCP as that would mean there's another issue I'm unaware of. If so I'd like to know if this is the first time you opened the app or not, and which games you've added/removed.

**Comment by mintyc** [comment]
> In the meantime you can delete your current app data for the program by deleting the files at `%localappdata%\Rayman Control Panel\RCP_Metro`

Having deleted the contents of that location, the control panel appears to run now - didn't find many of the games I have but I'm sure I'll be able to manually locate and enable them.

The speed of your reply was amazing. Your tool is a fantastic step for Rayman addicts everywhere.

Lets hope I can get my latest PC Rayman M 2 CD install to work as well once I have the control panel working on everything else!

**Comment by RayCarrot** [comment]
I'm glad it works now!

**Comment by mintyc** [comment]
I did hunt high and low to find a way to thank you. I know you do this as a passion, but a way to donate to you or perhaps help fund some of the costs you incur (hosting, pc etc) would let a very large community thank you in a more tangible way.

**Comment by RayCarrot** [comment]
I really appreciate the offer, but I don't want to accept any donations at this time. Thanks for the offer though! I'm glad you find the program useful! :)
