### ISSUE TITLE
Rayman 2 - Translations Text Editor ?

### ISSUE THREAD

**Issue by jy95** [RayCarrot/RayCarrot.RCP.Metro#26]
Hello @RayCarrot and others,

First and foremost, thanks for the tool : quite an interesting project ;)
I was wondering if you have a recommanded way to see contained translations in a fix.sna file (since RCP has a decoding tool for sna files).

Because RaymanTextTool links seem to be down : 

![image](https://github.com/RayCarrot/RayCarrot.RCP.Metro/assets/9306961/4bf88794-fd1e-4972-a680-82b4243def32)

Thanks in advance

**Comment by RayCarrot** [comment]
Hi! I still have it on my computer, so I'll upload it here for you.
[Rayman 2 Text Tool.zip](https://github.com/RayCarrot/RayCarrot.RCP.Metro/files/14549800/Rayman.2.Text.Tool.zip)

**Comment by jy95** [comment]
Thank you, have a nice day 😎
