### ISSUE TITLE
Question: Is it possible to use PS4/Xbox One assets in order to get instant loading times on the PC version of Rayman Legends?

### ISSUE THREAD

**Issue by Adamillo** [RayCarrot/RayCarrot.RCP.Metro#28]
I'm wondering if that would be even feasible to do? I do find it kinda interesting that the PS4 version of this game has quite a lot more IPK files compared to the PC version...

**Comment by RayCarrot** [comment]
Probably not through copying assets, but maybe there's some way to disable loading screens on PC. I'd imagine modern computers with SSDs should be able to load the levels pretty much instantly. In fact, if you force the game to run at an insanely high framerate then it will speed up the game and actually have the loading screens go by in less than a second.
But even if it'd be possible to remove the loading screens I wouldn't know how to do so.

Btw, do you want to join the Rayman Modding Discord server? Might be easier using that if you have any questions. If you add me on Discord I can send you an invite (my username is the same as here, but all lowercase).

**Comment by Adamillo** [comment]
Got it! Added you in Discord!
