### ISSUE TITLE
Configuration for Rayman Legends controls

### ISSUE THREAD

**Issue by Clozent** [RayCarrot/RayCarrot.RCP.Metro#29]
The app currently does not have many options available for Rayman Legends: the only available ones seem to come from the config.xml in the installation folder.

My guess is that most settings are simply kept in the save file of the game, if it can be decoded.

My main goal is to be able to assign two actions to the same button, because I am used to the Nintendo layout, and I want to assign both the cancel and jump actions to the B button.

**Comment by RayCarrot** [comment]
Hi! The settings in Rayman Legends are stored in the Registry key at `HKEY_CURRENT_USER\Software\Ubisoft\Rayman Legends`. You can open this directly from the config window in RCP. The `PlayerX` keys have the control configs for each player. You can try manually copying over values from specific inputs and see if it works. Perhaps in the future I can add this to RCP as well.

**Comment by Clozent** [comment]
Hi, thank you so much!

**Comment by Clozent** [comment]
Uhm, well, it turns out the game uses the jump button to accept.
This means that I can't use the B button for both jump and back, because the game will just use B to accept...
Perhaps another key can be made in the registry to specify the accept button?

**Comment by RayCarrot** [comment]
I'd imagine you'd have to edit the exe for that then, and I don't really know how the game handles inputs
