### ISSUE TITLE
Want to include rayman arena network init patch?

### ISSUE THREAD

**Issue by zZeck** [RayCarrot/RayCarrot.RCP.Metro#3]
[I made it](https://github.com/zZeck/RaymanArenaPatch).

Inspired by [this issue](https://github.com/zZeck/RaymanArenaPatch/issues/2).

I can probably make a PR for this repo, if you do want it.

**Comment by zZeck** [comment]
My patch is updated now finally. It looks in the rayman arena directory for arenaPatch.cfg and reads from it the network adapter name. If it finds a matching adapter, it will be used without prompting the user.

**Comment by RayCarrot** [comment]
Hi again and sorry for such a late reply!
In the latest beta (and soon to be final release) I've added a new "patcher" feature (basically a sort of mod loader). Moving forward I'm going to try and have game file modifications made by RCP use this new system as it allows them to easily be reverted and such. I'm thinking for your network patch that this might be a good way to go? If you make a patch for it I can upload it as one of the downloadable patches in RCP, thus making it available directly in the patcher window for Rayman Arena.

**Comment by zZeck** [comment]
No worries. I've been and continue to be occupied with various projects.

This patch needs dll injection to load, since it runs code to open up a network select menu on the first run, and read the config file on runs after that.

The patch has expanded, since it now includes discord presence support as well, which runs in its own thread.

What would I need to do?

**Comment by RayCarrot** [comment]
Assuming it just needs to add or replace files in the game directory you can create a patch in RCP by going to `Utilities > Patch Creator`, choose `Rayman Arena` as the game and create a new patch. There you specify the patch metadata and add the files (either from a folder or one by one). Once created you'll have a .gp patch file which can be added in the patcher dialog (in the games drop-down menu). You can upload this file here and I can upload it to be listed as a downloadable patch (like what you can currently see for Rayman 2 and 3 which each has a downloadable patch).

**Comment by zZeck** [comment]
Would it be acceptable to bundle something like an ASI loader dll then, to get the game to do the dll injection? Normally I think asi loader expects the injected dlls to be in a subdirectory. There are probably other dll injectors that could replace a dll the game uses, and might be able to load my dll from the game root. Maybe asi loader can be configured to do that. Not sure.

**Comment by zZeck** [comment]
Or is the patch system able to move a directory too? Then I could have it move a plugins directory for asi loader, with my dll in it, and move the asi dll into the root.

**Comment by RayCarrot** [comment]
You can't move existing files, but you can add files in new directories and deleting existing files which would essentially result in the same thing. If you leave the source path empty in the creator it will delete the file at the destination path rather than add/replace the file.

**Comment by RayCarrot** [comment]
Just checking in here - any progress on creating the patch in RCP?

**Comment by zZeck** [comment]
Sorry. I do mean to get back to this. Been occupied with other projects. Dunno if you saw the [rayman arena decompilation](https://github.com/zZeck/raymanarenadecomp), but that's one of them. I think I'll probably get back to this later this week. though, since you've reminded me. XD

**Comment by zZeck** [comment]
Did I do this right? Put the gp file in a zip so I could upload it to github. Has the asi loader dinput8.dll, and then puts my patch .asi into /plugins.
[arenaMultiplayerPatch.zip](https://github.com/RayCarrot/RayCarrot.RCP.Metro/files/9738359/arenaMultiplayerPatch.zip)

**Comment by RayCarrot** [comment]
The patch has now been added. Thanks!
