### ISSUE TITLE
(Rayman 2) Native controller support stucked

### ISSUE THREAD

**Issue by EngineerGlitch** [RayCarrot/RayCarrot.RCP.Metro#34]
I enabled native controller support, but when I deactivate it, it's still enable in the game, how can I fix it ?

![Capture d’écran 2024-09-02 140732](https://github.com/user-attachments/assets/03263b4d-1694-434b-b7c7-9139ddd48d54)

**Comment by RayCarrot** [comment]
Perhaps you're using another mod like Ray2Fix which also enables it?

**Comment by EngineerGlitch** [comment]
Hello @RayCarrot , no mod activated

![image](https://github.com/user-attachments/assets/32438216-4f76-480f-8706-4a09815bccf8)

**Comment by RayCarrot** [comment]
Sorry for taking so long to get back to this. Did you resolve the issue? Also what exactly do you mean by it still being enabled in the game?

**Comment by EngineerGlitch** [comment]
Checked and found no more problem, I can finally play with a Wiimote perfectly lol, I guess you can close the issue, 
merry Christmas btw 👍

**Comment by RayCarrot** [comment]
I'm glad it's all working! Merry Christmas! 🙂
