### ISSUE TITLE
RAYMAN CONTROL PANEL NOT SUPPORTED ON LINUX

### ISSUE THREAD

**Issue by RetroCube64** [RayCarrot/RayCarrot.RCP.Metro#35]
Hello RayCarrot

I had windows for years and i installed rayman control panel years ago, so i wanted to move to pop os (its an linux os)
when i was trying to install rayman control panel it wasnt supported on linux i tried everything but nothing worked
i cant make an level or gets mods and even dlcs fan so please can you make a version of linux

BY- Taim Nassar

Username on discord: wrencreal

**Comment by RetroCube64** [comment]
will wine help ? (wine is an app that can run 32bits exe)

**Comment by RayCarrot** [comment]
In theory yeah, but I've heard reports from others that they have trouble getting the newer versions of this app to run there. I don't have Linux myself so I can't verify it.
