### ISSUE TITLE
Enabling native controller support in Rayman M causes crash during first loading screen

### ISSUE THREAD

**Issue by TheAlp** [RayCarrot/RayCarrot.RCP.Metro#5]
As the title says, any time you launch the game with the dinput8.dll file enabled I can't reach the main menu. Not quite sure what causes this.

**Comment by RayCarrot** [comment]
Which version of Rayman M are you using?

**Comment by TheAlp** [comment]
I've tried both the standard one and the remake from [myabandonware](https://www.myabandonware.com/game/rayman-arena-e6h).

**Comment by RayCarrot** [comment]
Which standard version are you using? It works fine for all the versions I've tested it on. I'm not sure why it would cause it to crash. Have you tried setting the game exe to use compatibility mode and run as admin?
