### ISSUE TITLE
[Rayman M] Issues with the Polish version.

### ISSUE THREAD

**Issue by justtoask** [RayCarrot/RayCarrot.RCP.Metro#8]
I've noticed two issues with the Polish version of rayman M and RCP:

1. The discs for the game don't contain the file `outro.bik` and you can't install the game using RCP because of that.
2. The Polish language was added to the game, by added I mean it doesn't replace english, but you can't pick it as a language in RCP so every time you make changes there you also have to change the language in `ubi.ini` manually.

**Comment by RayCarrot** [comment]
Ah thanks for letting me know! I'll mark the outro file as optional for now then. As for the language, does it set it to "Polish" in the ini file? Does it replace another language or are all the other ones still there?

**Comment by justtoask** [comment]
It sets the language as "Polish" in the ini file and it doesn't replace all the other languages from what it seems.

**Comment by justtoask** [comment]
Also, can you include the Polish translation for Rayman 2> it's made by the Polish publisher, but not included in digital releases: https://disk.yandex.ru/d/VaZBFOgT3QRGto

**Comment by RayCarrot** [comment]
> It sets the language as "Polish" in the ini file and it doesn't replace all the other languages from what it seems.
Ok, thanks! I'll have a look at adding that later.

> Also, can you include the Polish translation for Rayman 2 in RCP? it's made by the Polish publisher, but not included in digital releases.
Probably not. That version modified a lot more files than the translations RCP can download right now.

**Comment by RayCarrot** [comment]
> It sets the language as "Polish" in the ini file and it doesn't replace all the other languages from what it seems.

I just installed the Polish version and it seems to run in Polish no matter which language I choose. The only place the language option seems to matter is for the RM_Setup_DX8 program which indeed allows Polish as an additional language. Is this what you meant or do you have a release where the game itself is effected too?
