### ISSUE TITLE
Engine

### ISSUE THREAD

**Issue by Bezdrom** [RayCarrot/RayCarrot.RCP.Metro#9]
Hello. Do you know which engine Just dance and Rayman Origin uses?

**Comment by RayCarrot** [comment]
[UbiArt Framework](https://en.wikipedia.org/wiki/UbiArt_Framework)

**Comment by Bezdrom** [comment]
Do you know how to change parameters in .exe to add your settings?

**Comment by RayCarrot** [comment]
Add which settings?

**Comment by Bezdrom** [comment]
Example: new logic for hud

**Comment by Bezdrom** [comment]
> This program has no settings to add new logic for hud in any UbiArt game. I'm not really sure what you're getting at, but if it's not related to this program (Rayman Control Panel) then I'll be closing the issue.

Ah. Oki
